# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn1'
    subscriptionId: 'c519682f-6b76-447e-b894-65a425a7f8d1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'South India'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/LinkedTemplate.json'
    overrideParameters: '-projectName myFirstTemplateDemo -linkedTemplateUri -https://raw.githubusercontent.com/shikhagupta2020/testrepo/master/CreateWebApp/LinkedTemplate.json'
    deploymentMode: 'Incremental'
    deploymentName: 'myFirstDeployemnt'
  displayName: 'Run a one-line script'

- script: |
   
  displayName: 'Run a multi-line script'
